import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export async function getServerSideProps() {
  const today = Date.now();
  const isodate = today.toISOString().substring(0,10);
  const apiKey = 'szzVynFpZcg8X6UZ37YHHr5jOCXwII4RDGpBO8XL';
  
  const url = `https://api.nasa.gov/neo/rest/v1/feed?start_date=${isodate}&end_date=${isodate}&api_key=${apiKey}`;
  
  // Fetch data from external API
  const res = await fetch(url);
  const data = await res.json();

  // Transform data
  const payload = data.near_earth_objects;
  const rows = [];
  Object.entries(payload).forEach(entry => {
    const [key, value] = entry;
    value.forEach(neo => {
      const row = {
        name: neo.name,
        jplUrl: neo.nasa_jpl_url,
        isHazardous: neo.is_potentially_hazardous_asteroid,
        approachDate: neo.close_approach_data.close_approach_date_full,
        missDistance: neo.close_approach_data.miss_distance.kilometers,
        relativeVelocity: neo.close_approach_data.relative_velocity.kilometers_per_hour,
        diameterMin: neo.estimated_diameter.meters.estimated_diameter_min,
        diameterMax: neo.estimated_diameter.meters.estimated_diameter_max
      };
      rows.push(row);
    });
  });

  // Pass data to the page via props
  return { props: { rows } }
}

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
